import json
from pathlib import Path
P=Path(__file__).parent
nodes={r['id']:r for r in map(json.loads,(P/'nodes.jsonl').read_text().splitlines())}
edges={r['key']:r for r in map(json.loads,(P/'edges.jsonl').read_text().splitlines())}
reviews=[]
def node(id,verdict,reason,proposal):
 n=nodes[id];reviews.append({'kind':'node','id':id,'discipline':n['discipline'],'before':n['statement'],'sourceExcerpt':n['source'],'location':n['location'],'verdict':verdict,'reason':reason,'proposal':proposal,'reviewLevel':'model-semantic-review','sourceVerification':'stored-excerpt-only; original PDF not inspected','applied':False})
def edge(key,reason,proposal,verdict='revise-or-retype'):
 e=edges[key];reviews.append({'kind':'edge','id':key,'discipline':e['discipline'],'before':{'prerequisite':e['prerequisite'],'target':e['target'],'type':e['type'],'strength':e['strength'],'failure':e['failure']},'location':e['location'],'verdict':verdict,'reason':reason,'proposal':proposal,'reviewLevel':'model-semantic-review','sourceVerification':'stored endpoints and reasoning; no learner validation','applied':False})
# Exact problematic metacognitive rewrites: all 12 matches were read, not all mentions of teachers.
for n in nodes.values():
 if 'A05' in n['flags']:
  direct=n['source'];node(n['id'],'restore-learning-action','把“学生实际完成行动”变成“复述学生应该做什么”，改变了测量对象。背出活动要求不能证明会做活动。源段若是教学建议，也不能伪装为强制课标达标项。','先核对源页所属栏目。若为内容要求，以原文学生行动为锚点：'+direct+'；若为教学建议，转入教学任务库并引用相应课标，不新增课标要求。')
node('ca_xkDNtkD2','reclassify-as-application-proposal','源句说明语言知识的性质，不直接要求学生掌握三维元语言分类。该转写可以作为教学分析工具，但不是每个学生的必达项。','保留推导身份，明确适用任务与支持条件；分别提供实际语境运用证据，不能用术语复述代替语言运用。')
node('ca_WWuRYQDZ','retain-as-limited-indicator','列举两个运动名称可观察，但“两项”的数量由设计者补入；命名不代表参与运动或安全技能。','标明数量为应用层评分约定；不向运动技能或安全掌握传播。')
node('ca_BEnaDVY6','restore-context','“这个问题”脱离母句后没有指代对象。拆分破坏了独立可理解性。','草案：给定一个网络传输问题，说明相关协议如何处理它。问题范围、可用资料与解释深度在任务层限定。')
node('ca_rnMsnSd5','do-not-substitute-performance','源段要求制作菜肴并参与完整过程；说出操作要点只覆盖知识性准备，不能覆盖实际制作。','保留为辅助知识指标；实践指标另用“在约定条件下完成一种适合的烹饪任务，并完成准备、制作、整理过程”，标教学切分草案。')
node('ca_Z5DfRE89','conditional-retain','从材料识别冶炼成就是合理的可观察任务，但源片段是材料主题，不能单凭主题证明课标规定了这个任务与数量。','作为材料研读任务引用原主题；原页上下文核对后决定是否独立课标能力。')
node('ca_cZn2LpYt','retain-with-assessment-boundary','能说出原因与源句知道原因大致一致；“至少两个”不是所引源句给出的标准。','数量移到示例任务评分说明，能力表述保留解释隋朝速亡原因，避免把背出两个词当解释充分。')
node('ca_7MqFXK3Y','partial-indicator-only','地图定位只是源句中地理位置/疆域要求的一部分，不能代表国家版图意识、海洋权益意识的全部。','标记 partial-indicator-of；地图定位独立核对，政治地理解释与价值构念分别保留证据。')
node('ca_d9HY2WWq','restore-probability-focus','源句重点是随机现象发生可能性的可预测性，列举随机现象只检查辨识，遗漏概率判断。','列举作为前置任务；另设计在给定重复试验/数据下比较可能性并说明不确定性的应用指标，不冒充源句原话。')
node('ca_HpBJwzvn','clarify-model-context','把“知道物理模型”变成判断一段描述是否使用模型，需理解实际对象与理想化模型的区别；可作为推导任务但需具体材料。','提供运动描述与被忽略条件，要求指出哪些是理想化假设；不把术语出现等同模型理解。')
node('ca_baqRCf9d','partial-indicator-only','指出雄蕊位置只检验识图，无法证明知道雄蕊/雌蕊的重要性或功能。','标记识图维度；另设结构功能解释指标，避免位置辨认代替生命观念。')
node('ca_NS7Fzf83','narrow-scope-and-verify-source','能力判断与解释可操作，但 G1–G6 跨度过大。所存定义把物理变化缩成状态改变，不能支持对任意变化的全域判别。','先查原页和年段；应用层限制为指定实例，以是否产生新物质为判断依据，明确宏观观察的局限，不自行设为一年级必达。')
node('ca_fxdVfb5z','retain-as-application-proposal','举例解释实用与美观能对应源段设计原则；“两件”属任务参数，产品使用情境决定实用性。','任务中给定使用者和用途，让学生比较形式与功能；保留设计理由而非只凭“好看”。')
node('ca_4b7t8N9A','restore-language-use-context','形式—意义—使用的统一被拆成孤立形式识别，可能鼓励脱离语境的术语命名。G1–G9 也不是精确难度。','作为语法分析子指标保留，必须和具体语境运用关联；不能因形式分析通过就判语言综合能力通过。')
node('ca_88cN56V3','partial-indicator-only','列出调查渠道只测规划，源文要求展开调查并获取材料；规划不是实际完成。','把调查规划和实际信息获取分开，分别保留证据；母项需两者支持而不是只答出渠道。')
node('ca_L7MpWpQt','retain-with-construct-boundary','说明成就与领导关系是解释性表现；不宜用单次解释直接推断持续价值认同，也需看具体史实与材料。','保留基于材料的解释任务；用材料、联系和理由评价解释，不替代长期价值与责任实践。')
node('ca_UKA5QsG6','repair-evidence-not-statement','既有裁决承认断言对应原文，却用这一点驳回口头分享不能证明书面评论的异议。这是审查维度混淆。','保留写评论的能力；替换证据为实际书面评论，含明确观点、作品细节支撑与论证组织。课程类型待源页核对。')
node('ca_VKU9hc8E','repair-split-evidence','拆成搅拌子项后仍复制包含搅拌和温度两个实验的母项证据，导致证据要求超出子项范围；知道因素到完成实验仍是推导。','证据草案：在明确的盐水实验条件下只改变搅拌，保持其他条件相同，记录一致的观察终点，并据记录说明结论与限制。保留紫圈。')
node('ca_d2XpK8Ar','repair-split-evidence','温度子项不应要求同时完成搅拌实验。既有裁决说明拆开合理，却没有修掉复制的母项证据。','证据草案：只改变水温，水量、盐量、搅拌等保持一致，以相同终点记录结果；表述仅覆盖实验条件，不宣称对所有物质普遍成立。保留紫圈。')
node('ca_F9rkKeDv','remove-unfounded-timing','所引课标写“熟练”，没有两秒阈值。现有单题两秒证据既是未声明的额外标准，也不能代表全部四则口算。','将响应时间作为任务参数而非课标要求；用覆盖典型运算的多题表现，分别记录准确性、策略与流畅程度。')
# Deliberate counterexamples for dependency validity; constituent-of is not instructional prerequisite-of.
edge('ca_dtBJHh92->ca_nuNiw3Mt','技术要领是多内容描述的组成部分；满足整体要求包含此部分，不等于必须先教此部分再教规则。','改进图层为 part-of，并给母项 AND 条件；不要作为学习顺序强约束。')
edge('ca_wzWtRgi8->ca_ps7EZeA5','自我保护与相互帮助可以在同一协作动作中学习，母子包含关系不证明先后；失败情境只是一个例子。','保留组成关系，按具体运动设操作条件及安全要求，不向所有项目泛化。')
edge('ca_UEyAGE7j->ca_tLb5SAqN','构词和语境是可以互相补偿的词义推断途径。缺少构词分析不必然无法从语境理解。','用 strategy-for/alternative-support 标示路径；若母项明确要求两种策略均会用，用 AND 聚合但不生成先修顺序。')
edge('ca_cs56grWe->ca_aVYvA7MP','推断未知词义的任务不能以已经掌握该词词义为必要前提；失败例却改成构词错误，未检验语境推断。','改成“熟悉周边语篇并识别语境线索”的限定支持条件；给定材料测试，不保留循环定义。')
edge('ca_xwPiEkqA->ca_QHwRWN5M','物理实验数据呈现只是报告的一种来源；信息技术报告可分析问卷或日志，不以物理实验表现为前提。','跨科改为共同数据分析维度或 transferable-support；保留数据类型/工具条件。')
edge('ca_84tSVY77->ca_XmzpLZXj','选择最优并改进方案比尝试评价一个方案要求更高。可评价单一方案而无需多方案综合选择。','撤销广义前置方向；拆“按标准评价”“比较权衡”“提出改进”为层次，作为待验证学习进阶。')
edge('ca_xN55mbW7->ca_fN4IHcRr','前置写网页工具，失败例却写不会在线写作工具，错点落到另一个子项。两种工具也可能互为替代。','修正失败例指向；确认源文的并列是任选还是全部，使用 OR/AND 聚合，不强制某个软件路径。')
edge('ca_BEnaDVY6->ca_L82Wxv3d','子句的“这个问题”依赖母句语境，不能当作无条件独立前置。TCP 只是示例，不应等于所有互联网协议。','补全问题指代并作为解释子表现；网络问题和协议机制一一对应后再审核。')
edge('ca_7uJkt5Af->ca_rnMsnSd5','失败例明确说会炒、不会煎炖，不能证明缺少前置“会说炒”。方向性证据反了。','保留内容组成，失败描述改成炒要点的实际缺失；母项与实际烹饪实践分离。')
edge('ca_aLiwzE69->ca_rnMsnSd5','作为三类知识的组成关系合理；例子把“加水没过食材”写成普遍炖法，具体标准应由任务菜式限定。','保留 part-of，操作要点按具体菜式和条件制定，不能用一种做法覆盖全部炖法。')
edge('ca_H76eUtzw->ca_e6279rGZ','综合问题包含物理性质等问题，并非都要写化学方程式；原边把某些任务的工具绝对化。','降为条件性支持，只对确实需要反应表示/计算的任务激活。')
edge('ca_H76eUtzw->ca_kNu5WjAj','定性解释生锈可以依靠铁与氧、水有关的证据，不要求先写配平方程式。不会配平不等于不能解释。','限定为定量反应分析的工具支持，广义现象解释不设置 hard。')
edge('ca_YsnQEavs->ca_4FJUss43','失败例说会长安却不会东京，缺的是另一个组成部分，并不支持该前置的缺失后果。','修正到长安部分实际缺失；母子边仅表示两对象覆盖。')
edge('ca_gDtAtbbB->ca_4FJUss43','东京在此是历史语境下的开封，脱离限定词容易与现代东京混淆；组成关系本身不证明先后。','节点补充历史时期和地名语境；保持 part-of 而非固定教学顺序。')
edge('ca_J8BGeCUf->ca_U5G7KYQT','对于明确依赖该地图信息的分析任务，提取信息是必要任务步骤；但不能推到所有地理分析。','保留任务内 requires-data；母子表示组成，注明地图类型与阅读条件。','conditional-retain')
edge('ca_crKsH96d->ca_SbE6UuQr','公转演示属于自转/公转共同要求的一部分，不等于先学公转才能学自转。','保留 part-of，两个演示子项独立核对；避免同一学生重复计分。')
edge('ca_xu2fZaD6->ca_DqJKZVYv','失败描述是只搜国家利益而漏其他主题；这不能作为不具备国家利益搜索能力的表现。','修正错点与前置一致；等方面可能是开放例举，不机械把每个主题设硬前提。')
edge('ca_75Wvz4BJ->ca_JfwTZu2b','可在已经提供的资料上分析全球特征，不必先独立搜集。资料获得与资料分析是不同能力。','instrument/conditional-support，显式标注“资料需自行获取”才激活。')
edge('ca_7A2bpEtp->ca_gJzyxcJG','整体包括两类解释，但第一类不会不代表无法阐述第二类，失败例把并列误写成因果。','part-of，并行核对两个解释目标，不作为学习先后。')
edge('ca_3u6e6nDJ->ca_qga37Ug5','比较日常和哲学思维需要具体案例，但无需先能概述所有常见思维活动。','缩窄为给定案例辨认/比较条件，用材料降低记忆要求。')
edge('ca_F9rkKeDv->ca_26TqD3kA','竖式的失败例是进位遗漏，不是表内乘法不会；口算熟练支持效率，但该例不能证明必要性。','分别拆乘法事实、位值、进位记录；纸笔算法任务中明确禁止/允许工具后检验支持关系。')
edge('ca_F9rkKeDv->ca_yyMBrshz','孩子可用五个筹码理解3+2与5−2互逆，即使尚未熟练全部乘除口算。强前提过大。','取消全四则流利度 hard；改为特定运算意义/可逆操作经验的条件性支持。')
edge('ca_8fzVCSEh->ca_9ARCrnE9','动词形式掌握是母项的一部分；混淆进行/结果不只由前置形式造成，需要语境与动词类别。','part-of，提供日语具体语境与可接受表达，不能用母子关系定义语法教学顺序。')
edge('ca_eU2k79E4->ca_9ARCrnE9','失败例同时包含助词/及物性问题，无法单独归因于ておく；不能用混合错误证明单一节点缺失。','重新设计最小对比材料，控制助词和动词形式，只检验准备表达。')
edge('ca_QdP6iQDj->ca_YP7G86fR','法语节奏组的失败例用汉语“一边…一边…”解释，缺法语语音环境，不能作为法语评估证据。','替换为具体法语语流片段及停顿/重音观察要求；关系按组成处理。')
edge('ca_j8g28KBb->ca_YP7G86fR','升调取决于句式和语用，并非句末一律上扬；子表现需在指定语境判断。','给定语音与语境的升调任务，保留 part-of，不将形式简单对应全部疑问意图。')
edge('ca_xwPiEkqA->ca_8agveE5P','引用证据可以直接引用观察记录、测量读数或已给材料，不必先能用表格/图像多方式展示。','取消广义 hard，数据展示作为工具支持；证据相关性和论证联系单独设指标。')
edge('ca_xwPiEkqA->ca_9tG7LZES','简单实验报告未必要求同时掌握多种图表；表格/图像是表达工具，不能把形式当结论质量。','按报告任务说明选用一种合适表达；区分数据记录、分析、书面组织。')
edge('ca_kM3pBbCz->ca_y8Ctiegg','失败例说能举非生物因素，不能举物种作用，未体现前置“非生物因素”的缺失。','修复反向失败例；保留两类作用的组成关系而非先后。')
edge('ca_JnRcwrKf->ca_y8Ctiegg','例子与物种作用子项缺失相关，但“种群特征”应具体到数量等对象，不能只写增多。','part-of，补充相互作用机制和条件；不过度推广为所有生态现象的先修。')
edge('ca_d2XpK8Ar->ca_nCCmJWwZ','失败例把计时管理问题归给温度知识，且“搅拌那杯和温度高那杯”可能同时改变两个变量。','把实验分别控制变量；计时记录与温度解释分开，母子关系用 AND 聚合。')
edge('ca_VKU9hc8E->ca_nCCmJWwZ','失败描述“只改变一个条件”可能恰是正确控制变量设计。不能将没有同时探究两因素当成搅拌能力缺失。','两组单变量任务分别核对搅拌和温度；母项覆盖两个任务，不能从一个失败归因两项。')
edge('ca_WbfPLXpb->ca_wg8cyq3C','表达态度可以通过口头、绘画等途径，无需先掌握手工制作。拿画笔发呆也不证明没有态度。','改为具体手工表达任务下的工具支持；恢复目标的创作媒介上下文。')
edge('ca_M4kbcNPL->ca_4VLRQt3M','低头沉默可能来自协作分工、交流方式或情境，不足以证明缺乏思想情感表达能力。','记录可观察作品贡献和多种表达方式；不以性格表现作为能力缺失证据。')
edge('ca_kMJGYbpW->ca_ViFhCEpr','编创与表现属于母项两个维度，可表现别人的作品而不会编创。','part-of；不要让编创成为表演能力的普遍强前提。')
edge('ca_H3MjYiKy->ca_ViFhCEpr','失败例转向编创长短变化，未隔离表现能力；节奏重复变化可以不只通过时值变化。','用给定节奏/旋律复现任务检测表现，编创任务另测。')
edge('ca_z2f4UFRi->ca_XFNvmxAS','主语用法可作为组合语法能力的子项，示例Swim is fun能针对形式差异，但需排除拼写/指令误解。','保留组成边，母项按各语法角色覆盖，不引申为必先学主语后学宾语。','conditional-retain')
edge('ca_vuumhRjU->ca_XFNvmxAS','I like to run 本身可以是合语法表达；未使用题目目标形式不等于句子错误。原例混淆了目标结构展示与语法正误。','区分“未展示 -ing 目标结构”与“语法错误”；在明确要求目标形式的任务中评估。')
edge('ca_hexu53aC->ca_Q4xGAthA','失败例说能说单词却不能组合词组，缺少的是组合能力，不能证明单词能力缺失。','修正到单词命名失败；词组/句子组合单独测，关系为组成。')
edge('ca_CcRzXg2w->ca_tvsaq4R6','用贺卡模板提取活动时间地点不一定合理；邀请函与贺卡文体要求不同，等字也可能表示开放例举。','保留文体实例关系，任务按交际目的选择，不把每种文体都机械设必达子项。')
edge('ca_GyQEdbby->ca_5DS8mPj4','基本字表不是构字部件表；能写复杂字不逻辑要求已会整张基本字表。单一笔画错误也无法支持整个清单依赖。','改为基于实际字形/笔画的局部支持，清单覆盖用集合关系，不设置整表 hard。')
edge('ca_npnfQi7n->ca_UiMzwsV6','拼读与书写是并列维度；例子同时涉及声调与形近字母书写，不能把写错全归于不会拼读。','part-of，并分别采集语音输出与书写产物。')
edge('ca_KYGdbMPR->ca_ADXSSyGn','失败例表示能画草图但不会三视图，错点在另一个子项；草图和三视图也有不同表达目标。','修正失败指向，组成与技术交流综合任务分开。')
edge('ca_2TJPcwEy->ca_ADXSSyGn','投影关系错误可针对三视图子项，但草图、三视图、交流不应形成无条件线性顺序。','part-of；按给定构件与制图约定核验三视图。','conditional-retain')
edge('ca_L7MpWpQt->ca_NPBYw8dv','解释关系可作为“举例并解释”的部分；至少两个为转写任务阈值，不是所引课标给出的普遍标准。','保留组成与阈值来源，具体例子和解释联系分开核对。')
edge('ca_izKZmkzH->ca_jeRVG4cP','失败描述只是重复子项做不出来，没给可辨别的材料/回答/错点，仍然循环论证。','补具体材料与可观察解释差异；母子关系不自动变成教学先修。')
edge('ca_69MNdFnu->ca_7LjDZDeW','听辨音乐要素不要求能演唱主题，演唱技巧与听觉理解可不同步。','听辨/标注材料可作为替代路径，演唱为可选支持。')
edge('ca_7LjDZDeW->ca_vuJuAYYz','简单剪切、拼接等软件编辑不都要求先解释音乐情感；目标包含工具与创作多个维度。','把工具编辑与表达性创作分开；情感分析只支持特定创作目标，保留地区条件。')
(P/'deep-review.jsonl').write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in reviews))
print('deep reviews',len(reviews),'nodes',sum(r['kind']=='node' for r in reviews),'edges',sum(r['kind']=='edge' for r in reviews))
